spring:
  profiles:
    active: prod

  application:
    name: OOPS
  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: dev



  datasource:
    url: jdbc:postgresql://localhost:5432/menudb?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate    # we validate against the existing schema
    show-sql: true
    properties:
      hibernate:
        # keep naming predictable; optional, but helps
        default_schema: public

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.tool.schema: DEBUG

---
# Production profile (Render)
spring:
  config:
    activate:
      on-profile: prod


  sql:
    init:
      mode: always          # run schema.sql / data.sql on startup
      continue-on-error: true  # optional: don’t fail if objects already exist

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none        # let schema.sql own the schema (recommended)
    show-sql: false
    properties:
      hibernate:
        default_schema: public

server:
  port: ${PORT:8080}

logging:
  level:
    org.hibernate.tool.schema: ERROR
    org.example.oops: INFO
    org.springframework.security: WARN
    org.springframework.jdbc.core: DEBUG
    com.zaxxer.hikari: DEBUG