spring:
  profiles:
    active: dev

---
# DEV = H2 (file on disk, so it persists between runs)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./.h2/menudb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none        # use schema.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always          # run schema.sql + data.sql
  h2:
    console:
      enabled: true

---
# LOCALPG = your Postgres (switch to this once password works)
spring:
  config:
    activate:
      on-profile: localpg
  datasource:
    url: jdbc:postgresql://localhost:5432/menudb
    username: postgres
    password: YOUR_PASSWORD
  jpa:
    hibernate:
      ddl-auto: none        # use schema.sql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
